Repository DO-SOPT-CodingTestStudy/studyArchive, pull requests merged in 2023-12, with the labels that each got.

#75 [7주차] 강원용 문제 제출
  KWY/DP/BAEK_GOLD5_동전1.java
  KWY/Floyd-Warshall/PROG_LEVEL2_배달.java
  KWY/HASH/PROG_LEVEL2_오픈채팅방.java
Labels: Java, 7주차, DP

#76 [7주차] 최승준 문제 제출
  CSJ/Arrays/prog_level2_신고_결과_받기.java
  CSJ/BFS&DFS/prog_level3_네트워크.java
  CSJ/grid/prog_level2_구명보트.java
Labels: Java, 그리디, 7주차

#77 [7주차] 강수경 문제 제출
  KSK/SQL/prog_level4_그룹별 조건에 맞는 식당 목록 출력하기.sql
  KSK/dp/prog_level3_N으로 표현.py
  KSK/스택,큐/prog_level2_뒤에 있는 큰 수 찾기.py
Labels: Python, 7주차, DP

#78 [7주차] 이성민 문제 제출
  SML/DIJKSTRA/prog_lvl3_가장 먼 노드.swift
  SML/RECURSION/prog_lvl2_괄호 변환.swift
  SML/구현/prog_lvl2_[3차] n진수 게임.swift
  SML/구현/prog_lvl2_수식 최대화.swift
Labels: Swift, 그리디, 7주차

#80 [7주차] 김가현 문제 제출
  KGH/DynamicProgramming/baekjoon_silver1_RGB거리.py
  KGH/DynamicProgramming/baekjoon_silver2_가장긴증가하는부분수열.py
  KGH/DynamicProgramming/baekjoon_silver3_1로만들기.py
Labels: Python, 7주차, DP

#81 [7주차] 권은빈 문제 제출
  KEB/DP/prog_level2_멀리뛰기.js
  KEB/DP/prog_level2_피보나치수.js
  KEB/ETC/prog_level1_콜라츠추측.js
Labels: JavaScript, 7주차, DP

#84 [8주차] 최승준 문제 제출
  CSJ/BFS&DFS/prog_level3_단어_변환.java
  CSJ/DP/prog_level4_도둑질.java
  CSJ/Math/prog_level1_콜라츠_추측.java
Labels: Java, 8주차, DFS/BFS

#82 [7주차] 이자민 문제 제출
  LJM/Recommend/prog_level2_짝지어 제거하기.py
  LJM/Recommend/prog_level_2_최댓값과 최솟값
Labels: Python, 7주차, DP

#92 [9주차] 이자민 문제제출
  LJM/Recommend/prog_level2_예상 대진표.py
  LJM/Recommend/prog_level2_할인 행사.py
  LJM/Recommend/prog_level_2_최댓값과 최솟값.py
  LJM/이분탐색/prog_level3_입국심사.py
  LJM/탐욕법/prog_level1_체육복.py
Labels: Python, 9주차, 이분탐색

#91 [9주차] 이재훈 문제제출
  LJH/BinarySearch/back_1920_수찾기.cpp
  LJH/Heap/prog_level3_이중우선순위큐.cpp
  LJH/Implementation/prog_level2_할인행사.cpp
Labels: C++, 9주차

#90 [9주차] 이성민 문제 제출
  SML/DFS, BFS/prog_lvl3_네트워크.swift
  SML/DFS, BFS/prog_lvl3_퍼즐 조각 채우기.swift
  SML/구현/prog_lvl3_[1차] 셔틀버스.swift
  SML/구현/prog_lvl3_[1차] 추석 트래픽.swift
  SML/구현/prog_lvl3_불량 사용자.swift
Labels: Swift, 9주차

#89 [9주차] 권은빈 문제제출
  KEB/BINARY_SEARCH/prog_level1_예산.js
  KEB/ETC/prog_level1_숫자문자열과영단어.js
  KEB/STACK,QUEUE/prog_level2_올바른괄호.js
Labels: JavaScript, 9주차, 이분탐색

#88 [9주차] 박현정 문제제출
  PHJ/binarysearch/baek_silver4_17266.cpp
Labels: C++, 9주차, 이분탐색

#86 [9주차]강수경 문제 제출
  KSK/greedy/prog_level1_체육복.py
  KSK/greedy/prog_level2_큰수만들기.py
  KSK/greedy/prog_level3_단속카메라.py
  KSK/greedy/prog_level3_최고의집합.py
  KSK/hash/prog_level2_전화번호목록.py
  KSK/heap/prog_level2_더맵게.py
  KSK/heap/softeer_level3_강의실배정.py
  KSK/스택,큐/prog_level2_이중우선순위큐.py
  KSK/완전탐색/prog_level2_소수찾기.py
Labels: Python, 9주차

#101 [10주차] 이재훈 문제제출
  LJH/BFS/back_gold5_토마토.cpp
Labels: C++, DFS/BFS, 10주차

#100 [10주차] 권은빈 문제제출
  KEB/BRUTE_FORCE/prog_level1_최소직사각형.js
  KEB/ETC/prog_level0_파샤드수.js
  KEB/ETC/prog_level2_숫자의표현.js
Labels: JavaScript, 10주차

#99 [10주차] 이성민 문제제출
  SML/.DS_Store
  SML/DYNAMIC PROGRAMMING/prog_lvl4_올바른 괄호의 개수.swift
Labels: Swift, 10주차

#98 [10주차] 박현정 문제제출
  PHJ/graph/baek_gold5_1717.cpp
Labels: C++, 10주차, 그래프

#93 [10주차] 최승준 문제 제출
  CSJ/Arrays/prog_level1_달리기_경주.java
  CSJ/Arrays/prog_level1_제일_작은_수_제거하기.java
Labels: Java, 10주차, 그래프

#94 [10주차] 강원용 문제 제출
  KWY/Graph/BAEK_SILVER2_트리의부모찾기.java
  KWY/HASH/PROG_LEVEL2_할인행사.java
  KWY/Stack/PROG_LEVEL2_무인도여행.java
Labels: Java, 10주차, 그래프

#96 [10주차] 김가현 문제 제출
  KGH/Graph/baek_gold4_최소스패닝트리.py
Labels: Python, 10주차

#97 [10주차] 김응관 문제제출
  KEK/Graph/prog_level2_배달.py
  KEK/구현/prog_level2_혼자서 하는 틱택토 게임.py
  KEK/완전탐색/prog_level2_연속 부분 수열 합의 개수.py
Labels: Python, 10주차, 그래프

#95 [10주차] 강수경 문제 제출
  KSK/스택,큐/prog_level2_뒤에 있는 큰 수 찾기.py
  KSK/스택,큐/prog_level2_뒤에있는큰수찾기.py
Labels: Python, 10주차
