Repository DO-SOPT-CodingTestStudy/studyArchive, pull requests merged in 2023-10, with the labels that each got.

#1 [1주차] 강수경 문제 제출
  KSK/SQL/prog_level1_과일로만든아이스크림고르기.sql
  KSK/SQL/prog_level1_인기있는아이스크림.sql
  KSK/SQL/prog_level1_조건에맞는도서리스트출력하기.sql
  KSK/SQL/prog_level1_평균일일대여요금구하기.sql
  KSK/SQL/prog_level2_3월에태어난여성회원목록출력하기.sql
  KSK/bfs/prog_level2_게임맵최단거리.py
  KSK/bfs/prog_level2_미로탈출.py
  KSK/bfs/prog_level2_전력망을 둘로 나누기.py
  KSK/dfs/prog_level2_타겟넘버.py
  KSK/dp/prog_level3_정수삼각형.py
  KSK/그리디/prog_level3_단속카메라.py
  KSK/스택,큐/prog_level2_다리를지나는트럭.py
  KSK/완전탐색/prog_level1_모의고사.py
  KSK/완전탐색/prog_level1_최소직사각형.py
  KSK/완전탐색/prog_level2_모음사전.py
  KSK/완전탐색/prog_level2_카펫.py
  KSK/완전탐색/prog_level2_피로도.py
  KSK/이분탐색/prog_level3_입국심사.py
  KSK/이분탐색/prog_level4_징검다리.py
  KSK/해시/prog_level2_전화번호목록.py
Labels: 1주차, 해시, Python

#2 [1주차] 강원용 문제 제출
  KWY/BruteForce/PROG_LEVEL2_삼각달팽이.java
  KWY/DP/prog_level3_정수삼각형.java
  KWY/HASH/PROG_LEVEL2_전화번호목록.java
Labels: 1주차, 해시, Java

#3 [1주차] 최승준 문제 제출
  CSJ/Arrays/prog_level2_영어_끝말잇기.java
  CSJ/DP/prog_level2_2_x_n_타일링.java
  CSJ/hash/prog_level2_전화번호_목록.java
Labels: 1주차, 해시, Java

#4 [1주차] 권은빈 문제 제출
  KEB/GREEDY/prog_level0_개미군단.js
  KEB/HASH/prog_level1_완주하지 못한 선수.js
  KEB/STACK,QUEUE/prog_level1_같은 숫자는 싫어.js
Labels: 1주차, 해시, JavaScript

#7 [1주차] 박준혁 문제 제출
  .gitignore
  PJH/PJH/문자열/prog_level0_외계인_사전.swift
  PJH/PJH/수학/prog_level0_짝수_홀수_개수.swift
  PJH/PJH/수학/prog_level1_약수의_개수와_덧셈.swift
  PJH/PJH/해시/prog_level2_의상.swift
Labels: 1주차, 해시, Swift

#8 [1주차] 박현정 문제 풀이
  .DS_Store
  PHJ/.gitignore
  PHJ/hash/baek_silver1_2002_추월.cpp
Labels: 1주차, 해시, C++

#5 [1주차] 왕호은 문제 제출
  WHE/.vscode/c_cpp_properties.json
  WHE/.vscode/launch.json
  WHE/.vscode/tasks.json
  WHE/DFS/prog_lv4_매출하락최소화.cpp
  WHE/Hash/baek_silver2_4358_생태학.cpp
  WHE/Tree/prog_lv3_길찾기게임.cpp
Labels: 1주차, 해시, C++

#9 [1주차] 이재훈 문제제출
  LJH/.cph/.back_silver3_9375_패션왕신해빈.cpp_c35f6e0dede6da200c3ce3eabadd6290.prob
  LJH/.vscode/settings.json
  LJH/Hash/back_silver3_9375_패션왕신해빈.bin
  LJH/Hash/back_silver3_9375_패션왕신해빈.cpp
  LJH/Implementation/prog_level0_외계어사전.cpp
  LJH/Implementation/prog_level2_삼각형의완성조건(2).cpp
Labels: 1주차, 해시, C++

#10 [1주차] 김응관 문제제출
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/studyArchive.iml
  .idea/vcs.xml
  KEK/Hash/prog_level1_성격 유형 검사하기.py
  KEK/Hash/prog_level2_우박수열 정적분.py
  KEK/Hash/prog_level2_테이블 해시 함수.py
  KEK/PriorityQueue/baek_silver1_카드합체놀이.py
  KEK/PriorityQueue/baek_silver2_최소 힙.py
  KEK/SQL/prog_level1_조건에 맞는 도서 리스트 출력하기.sql
  KEK/SQL/prog_level1_평균 일일 대여 요금 구하기.sql
  KEK/SQL/prog_level2_상품별 온라인 매출 구하기.sql
  KEK/SQL/prog_level2_조건에 맞는 도서와 저자 리스트 출력하기.sql
  KEK/SQL/prog_level2_카테고리 별 상품 개수 구하기.sql
  KEK/Search/prog_level0_안전지대.py
  KEK/문자열/prog_level0_저주의 숫자 3.py
  KEK/수학/직사각형 넓이 구하기.py
  KEK/스택/baek_gold4_오큰수.py
  KEK/완전탐색/prog_level0_옹알이 (1).py
Labels: 1주차, 해시, Python

#11 [2주차] 강원용 문제제출
  KWY/Implementation/PROG_LEVEL2_주차 요금 계산.java
  KWY/Stack/PROG_LEVEL2_프로세스.java
  KWY/String/PROG_LEVEL2_튜플.java
Labels: Java, 2주차, 스택/큐

#18 [2주차] 김응관 문제 제출
  KEK/스택/baek_gold2_후위 표기식.py
Labels: Python, 2주차, 스택/큐

#15 [2주차] 윤서진 문제 제출
  .DS_Store
  YSJ/DFS/prog_level3_네트워크.js
  YSJ/큐/prog_level2_프로세스.js
  YSJ/큐/prog_level3_이중우선순위큐.js
Labels: JavaScript, 2주차, 스택/큐

#16 [2주차] 송하윤 문제 제출
  SHY/BFS,DFS/prog_level3_네트워크.cpp
  SHY/SQL/prog_level5_상품을 구매한 회원 비율 구하기.sql
  SHY/StackQueue/back_silver3_24511_queueStack.cpp
Labels: C++, 2주차, 스택/큐

#20 [ 2주차 ] 권은빈 문제 제출
  KEB/GREEDY/prog_level1_체육복.js
  KEB/SORT/prog_level2_H-Index.js
  KEB/STACK,QUEUE/prog_level2_기능개발.js
Labels: JavaScript, 2주차, 스택/큐

#14 [2주차] 박현정 과제 제출
  PHJ/dfs, bfs/prog_leve3_가장 먼 노드.cpp
  PHJ/dp/prog_level4_올바른 괄호의 갯수.cpp
  PHJ/stack,queue/baek_silver2_1874_스택수열.cpp
Labels: C++, 2주차, 스택/큐

#22 [2주차] 이재훈 문제 제출
  LJH/.vscode/settings.json
  LJH/Implementation/prog_level1_명에의전당(1).cpp
  LJH/Implementation/prog_level_약수의합.cpp
  LJH/Stack/.cph/.boj_silver4_균형잡힌세상.cpp_e363fc2ad31d90f2fa2654e202c75147.prob
  LJH/Stack/boj_silver4_균형잡힌세상.bin
  LJH/Stack/boj_silver4_균형잡힌세상.cpp
Labels: C++, 2주차, 스택/큐

#21 [2주차] 최승준 문제 제출
  CSJ/heap/prog_level2_더_맵게.java
  CSJ/sort/prog_level2_H-Index.java
  CSJ/stack&queue/prog_level2_올바른_괄호.java
Labels: Java, 2주차, 스택/큐

#13 [2주차] 이성민 문제제출
  .DS_Store
  SML/.DS_Store
  SML/RECURSION/prog_lvl2_쿼드압축 후 개수 세기.swift
  SML/RECURSION/prog_lvl2_하노이의 탑.swift
  SML/STACK, QUEUE/prog_lvl2_다리를 지나는 트럭.swift
Labels: Swift, 2주차, 스택/큐

#23 [2주차] 박준혁 문제 제출
  .DS_Store
  .gitignore
  PJH/Stack/prog_level2_올바른_괄호.swift
  PJH/hash/prog_level2_의상.swift
  PJH/구현/prog_level1_없는_숫자_더하기.swift
  PJH/문자열/prog_level0_외계인_사전.swift
  PJH/수학/prog_level0_짝수_홀수_개수.swift
  PJH/수학/prog_level1_약수의_개수와_덧셈.swift
Labels: 1주차, 해시, Swift, 2주차, 스택/큐
