Repository DO-SOPT-CodingTestStudy/studyArchive, pull requests merged in 2023-11, with the labels that each got.

#36 [3주차] 최승준 문제 제출
  CSJ/BF/prog_level2_카펫.java
  CSJ/heap/prog_level3_이중우선순위큐.java
  CSJ/stack&queue/prog_level2_두_큐_합_같게_만들기.java
Labels: Java, 3주차, 힙

#35 [3주차] 권은빈 문제 제출
  KEB/HASH/prog_level1_폰켓몬.js
  KEB/HEAP/prog_level2_더맵게.js
  KEB/SORT/prog_level1_K번째수.js
Labels: JavaScript, 3주차, 힙

#34 [3주차] 박준혁 문제 제출
  PJH/DFS/prog_level3_네트워크.swift
  PJH/Heap/prog_level3_디스크_컨트롤러.swift
  PJH/탐색/prog_level3_입국심사.swift
Labels: Swift, 3주차, 힙

#33 [3주차] 이자민 문제 제출
  LJM/Heap/prog_level2_더 맵게.py
  LJM/Recommend/prog_level0_컨트롤제트.py
  LJM/Recommend/prog_level1_바탕화면 정리.py
Labels: Python, 3주차, 힙

#24 [3주차] 박현정 문제 제출
  PHJ/dfs, bfs/baek_silver1_2667.cpp
  PHJ/dp/prog_level3_거스름돈.cpp
  PHJ/dp/prog_level3_최적의 행렬 곱셈.cpp
  PHJ/heap/back_silver3_14235_크리스마스 선물.cpp
Labels: C++, 3주차, 힙

#25 [3주차] 강원용 문제 제출
  KWY/DivideAndConquer/PROG_LEVEL2_쿼드압축후개수세기.java
  KWY/Heap/PROG_LEVEL3_이중우선순위큐.java
  KWY/Sort/PROG_LEVEL2_최솟값만들기.java
Labels: Java, 3주차, 힙

#26 [3주차] 강수경 문제 해결
  KSK/SQL/prog_level1_강원도에 위치한 생산공장 목록 출력하기.sql
  KSK/SQL/prog_level1_동물의 아이디와 이름.sql
  KSK/SQL/prog_level1_아픈 동물 찾기.sql
  KSK/SQL/prog_level1_여러기준으로 정렬하기.sql
  KSK/SQL/prog_level1_조건에 부합하는 중고거래 댓글 조회하기.sql
  KSK/SQL/prog_level1_흉부외과 또는 일반외과 의사 목록 출력하기.sql
  KSK/SQL/prog_level4_오프라인/온라인 판매 데이터 통합하기.sql
  KSK/dp/softeer_level3_징검다리.py
  KSK/구현/baek_silver3_수열.py
  KSK/구현/softeer_level2_전광판.py
  KSK/구현/softeer_level3_수퍼바이러스.py
  KSK/완전탐색/softeer_level3_택배마스터광우.py
  KSK/힙/softeer_level3_강의실배정.py
Labels: Python, 3주차, 힙

#27 [3주차] 윤서진 문제 제출
  YSJ/구현/prog_level3_최고의집합.js
  YSJ/정렬/prog_level2_가장큰수.js
  YSJ/힙/prog_level2_더맵게.js
Labels: JavaScript, 3주차, 힙

#28 [3주차] 이성민 문제 제출
  SML/.DS_Store
  SML/DFS, BFS/prog_lvl2_전력망을 둘로 나누기.swift
  SML/HEAP/prog_lvl3_이중우선순위큐.swift
  SML/구현/prog_lvl2_주차 요금 계산.swift
  SML/완전탐색/prog_lvl3_합승 택시 요금.swift
Labels: Swift, 3주차, 힙

#29 [3주차] 이재훈 문제제출
  LJH/Heap/.cph/.back_silver1_15903_카드합체놀이.cpp_070174cd9d436c7666d97b4ece16ffe8.prob
  LJH/Heap/back_silver1_15903_카드합체놀이.bin
  LJH/Heap/back_silver1_15903_카드합체놀이.cpp
  LJH/Implementation/.cph/.prog_level_같은숫자는싫어.cpp_a0d80fd52e0611d1bd9fe0df67e3b946.prob
  LJH/Implementation/prog_level_같은숫자는싫어.bin
  LJH/Implementation/prog_level_같은숫자는싫어.cpp
  LJH/Recursive/prog_level2_하노이탑.cpp
  LJH/Stack/boj_silver4_균형잡힌세상.cpp
Labels: C++, 3주차, 힙

#30 [3주차] 김응관 문제제출
  KEK/PriorityQueue & Heap/baek_gold3_순회강연.py
  KEK/PriorityQueue & Heap/baek_silver1_절댓값 힙.py
  KEK/PriorityQueue & Heap/baek_silver1_카드합체놀이.py
  KEK/PriorityQueue & Heap/baek_silver2_최대 힙.py
  KEK/PriorityQueue & Heap/baek_silver2_최소 힙.py
  KEK/PriorityQueue & Heap/prog_level3_디스크 컨트롤러.py
  KEK/스택/baek_gold5_괄호의 값.py
  KEK/재귀/prog_level2_하노이의 탑.py
Labels: Python, 3주차, 힙

#31 [3주차] 송하윤 문제 제출
  SHY/Heap/back_gold2_1766_문제집.cpp
  SHY/Implement/prog_level3_택배배달과수거하기.cpp
  SHY/SQL/prog_level4_특정 기간동안 대여 가능한 자동차들의 대여비용 구하기.sql
Labels: C++, 3주차, 힙

#37 [3주차] 김가현 문제 제출
  KGH/BFS/prog_level3_단어변환.py
  KGH/Heap/prog_level2_더맵게.py
  KGH/Math/prog_level2_점프와순간이동.py
Labels: Python, 3주차, 힙

#38 [4주차] 강원용 문제 제출
  KWY/DP/PROG_LEVEL2_연속부분수열합의개수.java
  KWY/Sort/PROG_LEVEL2_HIndex.java
  KWY/Stack/PROG_LEVEL2_기능개발.java
Labels: Java, 4주차, 정렬

#40 [4주차] 강수경 문제 제출
  KSK/dp/prog_level4_올바른_괄호의_갯수.py
  KSK/구현/baek_silver3_수열.py
  KSK/그리디/prog_level3_최고의집합.py
  KSK/정렬/baek_platinum4_숫자의신.py
Labels: Python, 4주차, 정렬

#41 [4주차] 윤서진 문제 제출
  YSJ/DFS/prog_level2_타겟넘버.js
  YSJ/DP/prog_level3_N으로표현.js
  YSJ/정렬/백준_브론즈_세수정렬.js
  YSJ/정렬/백준_브론즈_수정렬하기.js
  YSJ/정렬/백준_브론즈_수정렬하기2.js
  YSJ/정렬/백준_실버_K번째수.js
Labels: JavaScript, 4주차, 정렬

#42 [4주차] 김응관 문제제출
  KEK/DP/prog_level3_정수 삼각형.py
  KEK/구현/prog_level2_n진수 게임.py
  KEK/스택/baek_gold5_탑.py
  KEK/정렬/baek_gold4_전화번호 목록.py
  KEK/정렬/baek_gold5_두 용액.py
  KEK/정렬/baek_silver3_빈도 정렬.py
  KEK/정렬/baek_silver5_점수 계산.py
Labels: Python, 4주차, 정렬

#43 [4주차] 송하윤 문제 제출
  SHY/BFS,DFS/prog_level2_타겟넘버.cpp
  SHY/SQL/prog_level4_5월 식품들의 총매출 조회하기.sql
  SHY/Sort/back_gold3_줄세우기_2252.cpp
Labels: C++, 4주차, 정렬

#44 [4주차] 이성민 문제 제출
  SML/.DS_Store
  SML/STACK, QUEUE/prog_lvl2_프로세스.swift
  SML/구현/prog_lvl2_삼각 달팽이.swift
  SML/정렬/prog_lvl2_[3차] 파일명 정렬.swift
Labels: Swift, 4주차, 정렬

#45 [4주차] 김가현 문제 제출
  KGH/Greedy/prog_level1_체육복.py
  KGH/Sort/prog_level1_K번째수.py
  KGH/Sort/prog_level2_가장큰수.py
Labels: Python, 4주차, 정렬

#47 [4주차] 최승준 문제 제출
  CSJ/BFS&DFS/prog_level3_단어_변환.py
  CSJ/BFS&DFS/prog_level3_여행_경로.py
  CSJ/sort/prog_level2_가장_큰_수.java
Labels: Java, 4주차, 정렬

#51 [4주차] 이재훈 문제제출
  LJH/.vscode/settings.json
  LJH/Implementation/prog_level1_카드뭉치
  LJH/Implementation/prog_level_같은숫자는싫어.cpp
  LJH/Implementation/prog_levle1_문자열다루기기본.cpp
  LJH/Sort/.cph/.back_silver5_단어정렬.cpp_a243d9da66510429a3c0aadd80a5d5ef.prob
  LJH/Sort/back_silver5_단어정렬.bin
  LJH/Sort/back_silver5_단어정렬.cpp
Labels: C++, 4주차, 정렬

#50 [4주차] 이자민 문제 제출
  LJM/Recommend/prog_level1_예산.py
  LJM/Recommend/prog_level2_두 원 사이의 정수 쌍.py
  LJM/정렬/prog_level2_가장 큰 수.py
Labels: Python, 4주차, 정렬

#49 [4주차] 권은빈 문제 제출
  KEB/PRACTICE/prog_level1_나누어떨어지는숫자배열.js
  KEB/PRACTICE/prog_level1_숫자짝꿍.js
  KEB/SORT/prog_level1_문자열 내 마음대로 정렬하기.js
Labels: JavaScript, 4주차, 정렬

#48 [4주차] 박현정 문제 제출
  PHJ/backtracking/prog_level2_n-queen.cpp
  PHJ/dfs, bfs/prog_level2_3*n타일링.cpp
  PHJ/sort/baek_silver5_2822.cpp
Labels: C++, 4주차, 정렬

#46 [4주차] 박준혁 문제 제출
  PJH/문자열/prog_level2_최댓값과 최솟값.swift
  PJH/정렬/prog_level1_K번째수.swift
  PJH/탐색/prog_level3_풍선 터트리기.swift
Labels: Swift, 4주차, 정렬

#53 [5주차] 강수경 문제 제출
  KSK/구현/swea_d2_어디에_단어가_들어갈_수_있을까.py
  KSK/구현/swea_d2_패턴_마디의_길이.py
  KSK/구현/swea_d3_원안의_점.py
Labels: Python, 5주차, 완전탐색

#54 [5주차] 강원용 문제 제출
  KWY/BruteForce/PROG_LEVEL2_카펫.java
  KWY/Graph/PROG_LEVEL3_가장먼노드.java
  KWY/Graph/PROG_LEVEL3_순위.java
Labels: Java, 5주차, 완전탐색

#55 [5주차] 이성민 문제 제출
  SML/DFS, BFS/prog_lvl2_리코쳇 로봇.swift
  SML/완전탐색/prog_lvl1_모의고사.swift
  SML/정렬/prog_lvl1_달리기 경주.swift
Labels: Swift, 5주차, 완전탐색

#60 [5주차] 김응관 문제제출
  KEK/Search/prog_level3-네트워크.py
Labels: Python, 5주차, 완전탐색

#59 [5주차] 김가현 문제 제출
  KGH/BruteForce/baek_silver2_사탕게임.py
  KGH/BruteForce/prog_level1_최소직사각형.py
  KGH/BruteForce/모의고사.py
Labels: Python, 5주차, 브루트포스

#58 [5주차] 이재훈 문제제출
  LJH/ExhaustiveSearch/back_silver3_Four Squares.cpp
  LJH/Implementation/prog_level1_시저암호.cpp
  LJH/Implementation/prog_level_예산.cpp
Labels: C++, 5주차, 완전탐색

#57 [5주차] 윤서진 문제 제출
  YSJ/그리디/prog_level2_구명보트.js
  YSJ/완전탐색/prog_level1_최소직사각형.js
  YSJ/큐/prog_level2_올바른괄호.js
Labels: JavaScript, 5주차, 완전탐색

#56 [5주차] 박준혁 문제 제출
  PJH/DFS/prog_level3_단어 변환.swift
  PJH/Stack/prog_level2_괄호 회전하기.swift
  PJH/완전탐색/prog_level1_최소직사각형.swift
Labels: Swift, 5주차, 완전탐색

#62 [5주차] 박현정 문제제출
  PHJ/bruteforce/1063.cpp
Labels: C++, 5주차, 완전탐색

#61 [5주차] 최승준 문제 제출
  CSJ/BFS&DFS/prog_level2_타겟_넘버.java
Labels: Java, 5주차, 완전탐색

#63 [5주차] 이자민 문제 제출
  LJM/Recommend/prog_level1_푸드 파이트 대회.py
  LJM/Recommend/prog_level2_호텔대실.py
  LJM/완전탐색/prog_level_1_모의고사.py
Labels: Python, 5주차, 완전탐색

#64 [6주차] 강원용 문제 제출
  KWY/BruteForce/PROF_LEVEL1_숫자문자열과영단어.java
  KWY/BruteForce/PROF_LEVEL2_거리두기확인하기.java
  KWY/Greedy/PROG_LEVEL2_구명보트.java
  KWY/Math/PROF_LEVEL2_점프와순간이동.java
Labels: Java, 6주차, 그리디

#66 [6주차] 이성민 문제 제출
  SML/.DS_Store
  SML/BINARY SEARCH/prog_lvl3_금과 은 운반하기.swift
  SML/DIJKSTRA/prog_lvl2_배달.swift
  SML/STACK, QUEUE/prog_lvl2_두 큐 합 같게 만들기.swift
  SML/탐색/prog_lvl2_카펫.swift
Labels: 6주차, 그리디

#67 [6주차] 권은빈 문제 제출
  KEB/ETC/prog_level0_가운데가져오기.js
  KEB/GREEDY/prog_level2_큰수만들기.js
Labels: JavaScript, 6주차, 그리디

#69 [6주차] 송하윤 문제제출
  SHY/Implement/prog_level1_키패드누르기.cpp
  SHY/Sort/back_gold5_두용액_2470.cpp
Labels: C++, 6주차, 그리디

#70 [6주차] 강수경 문제 제출
  KSK/SQL/prog_level4_오프라인_온라인 판매 데이터 통합하기.sql
  KSK/구현/prog_level1_[pccp 기출문제] 1번.py
  KSK/그리디/prog_level1_체육복.py
Labels: Python, 6주차, 그리디

#74 [6주차] 이자민 문제 제출
  LJM/Recommend/prog_level2_디펜스 게임.py
  LJM/Recommend/탐욕법/prog_level1_체육복.py
Labels: Python, 6주차, 그리디

#73 [6주차] 최승준 문제 해결
  CSJ/dijkstra/prog_level3_가장_먼_노드.java
  CSJ/grid/prog_level1_체육복.java
Labels: Java, 6주차, 그리디

#72 [6주차] 박준혁 문제 제출
  PJH/그리디/prog_level1_체육복.swift
  PJH/완전탐색/prog_level2_피로도.swift
Labels: Swift, 6주차, 그리디
